1ser1n1/sort/PGS level2 42746 가장큰수.py
- https://school.programmers.co.kr/learn/courses/30/lessons/42746
=> Create code : 원세린 PGS level2 42746 가장큰수

beginner0107/정렬/소트인사이드.py, beginner0107/정렬/좌표 정렬하기.py, beginner0107/정렬/통계학.py
- [통계학] https://www.acmicpc.net/problem/2108
- [좌표 정렬하기] https://www.acmicpc.net/problem/11650
- [소트인사이드] https://www.acmicpc.net/problem/1427
- 쉬운거 3문제 풀었습니다.
=> Merge : 안승주 정렬

jian1114/implementation/이지안 BOJ 골드4 14500 테트로미노.py
- https://www.acmicpc.net/problem/14500
- 항상 브론즈, 실버 문제만 풀다가 골드 문제를 풀다보니 어려운 점이 있었습니다.
- DFS 공부를 이제 시작해서 어려움이 있었는데 이해를 하고나면 재밌는(?) 것 같습니다ㅎㅎ
=> Create code : 이지안 BOJ 골드4 14500 테트로미노

ParkRang/BOJ 골드4 2831 댄스 파티.py, ParkRang/Greedy/BOJ 골드5 11509 풍선 맞추기.py, ParkRang/Greedy/BOJ 실버4 1026 보물.py, ParkRang/Greedy/BOJ 실버4 1246 온라인 판매.py
- https://www.acmicpc.net/problem/2831
- https://www.acmicpc.net/problem/11509
- https://www.acmicpc.net/problem/1246
- https://www.acmicpc.net/problem/1026
- 댄스 파티를 풀어보며 그리디 같은 경우 반복문을 최소한으로 줄이는 것이 중요하다는 것을 느끼게 되었습니다.
- 그리디에 대한 공부를 더 해보며, 이후에 나올 그리디에 대해서도 이렇게 대처를 하면 되겠구나 싶었습니다.
=> Create code : 박진우 그리디

ParkRang/BOJ 골드4 2831 댄스 파티.py
=> Fix code : 박진우 BOJ 골드4 2831 댄스 파티

beginner0107/해시/댄스파티.py, beginner0107/해시/성격유형검사하기.py, beginner0107/해시/전화번호 목록.py
- 댄스 파티: https://www.acmicpc.net/problem/2831
- 성격 유형 검사하기: https://school.programmers.co.kr/learn/courses/30/lessons/118666
- 전화번호 목록: https://school.programmers.co.kr/learn/courses/30/lessons/42577
- 간단하게 해시 문제 풀어봤습니다.
=> Create code : 안승주 해시

ayocado/BFS,DFS/PGS level3 43162 네트워크.py, ayocado/그리디/BOJ 골드4 2831 댄스파티.py
- BOJ 골드4 2831 댄스파티 : https://www.acmicpc.net/problem/2831
- PGS level3 43162 네트워크 : https://school.programmers.co.kr/learn/courses/30/lessons/43162
- DFS는 참 어렵네요 👎
=> Merge : 윤용완 DFS/BFS

bokkuembab/binary search/BOJ 실버2 2805 나무자르기.py, bokkuembab/stack/BOJ 실버2 1874 스택 수열.py
- https://www.acmicpc.net/problem/1874
- https://www.acmicpc.net/problem/2805
- 코마에서 이진 탐색 활용 문제가 있길래 연습 겸 풀어봤습니다!
=> Merge : 위예진 스택, 이진탐색

ayocado/BFS,DFS/BOJ 골드4 12851 숨바꼭질2.py, ayocado/BFS,DFS/BOJ 골드5 13549 숨바꼭질3.py, ayocado/BFS,DFS/BOJ 실버1 1697 숨바꼭질.py
- BOJ 실버1 1697 숨바꼭질 : https://www.acmicpc.net/problem/1697
- BOJ 골드4 12851 숨바꼭질2 : https://www.acmicpc.net/problem/12851
- BOJ 골드5 13549 숨바꼭질3 : https://www.acmicpc.net/problem/13549
- 숨바꼭질 시리즈를 풀어봤습니다! 모두 BFS를 이용했고, 마지막 '숨바꼭질4'는 시간초과로 아직 풀지 못했습니다. '숨바꼭질4'에 대해 조언주실 수 있는 분은 알려주시면 감사하겠습니다 👍
=> Merge : 윤용완 BFS

ParkRang/BOJ 골드5 13549 숨바꼭질 3.py, ParkRang/Binary_search/BOJ 골드4 2110 공유기 설치.py, ParkRang/Binary_search/BOJ 실버2 16401 과자 나눠주기.py, ParkRang/Binary_search/BOJ 실버4 1920 수 찾기.py
- https://www.acmicpc.net/problem/13549
- https://www.acmicpc.net/problem/2110
- https://www.acmicpc.net/problem/16401
- https://www.acmicpc.net/problem/1920
- 이진 탐색이 좀 편하지 않을까 해서 풀었는데 생각보다 어렵네요.
- 원리를 알게 되었으나 이를 실전에서 어떻게 이용할 수 있을지, 어떻게 사용하여야 할지는 아직 더 많은 경험이 필요할 것 같습니다.
=> Create code : 박진우 이진 탐색

bokkuembab/BFS/BOJ 실버1 1697 숨바꼭질.py, bokkuembab/BFS/BOJ 실버1 2178 미로 탐색.py, bokkuembab/BFS/BOJ 실버2 1260 DFS와 BFS.py
- https://www.acmicpc.net/problem/1260
- https://www.acmicpc.net/problem/2178
- https://www.acmicpc.net/problem/1697
- bfs 개념 및 구현 이해가 어려웠습니다..!
=> Merge : 위예진 BFS

Pang-dachu/DFS and BFS/김인재 BOJ 골드5 7569 토마토.py, Pang-dachu/DFS and BFS/김인재 BOJ 골드5 7576 토마토.py, Pang-dachu/Graph/BOJ 골5 숨바꼭질3.py, Pang-dachu/Graph/BOJ 실1 숨바꼭질.py
- https://www.acmicpc.net/problem/7569
- https://www.acmicpc.net/problem/7567
- https://www.acmicpc.net/problem/1697
- https://www.acmicpc.net/problem/13549
- 토마토 문제가 재미있다.
- 3차원은 머리가 아프다
=> Merge : 김인재 BFS

beginner0107/정렬/게임맵최단거리.java, beginner0107/정렬/게임맵최단거리.py, beginner0107/정렬/경로찾기.java, beginner0107/정렬/덧칠하기.java, beginner0107/정렬/덧칠하기.py, beginner0107/정렬/파일명정렬.java, beginner0107/정렬/파일명정렬.py
- 덧칠하기: https://school.programmers.co.kr/learn/courses/30/lessons/161989
- 게임 맵 최단거리: https://school.programmers.co.kr/learn/courses/30/lessons/1844
- 파일명 정렬: https://school.programmers.co.kr/learn/courses/30/lessons/17686
- 경로 찾기: https://www.acmicpc.net/problem/11403
- 공통문제인 토마토를 이전에 풀어두어서 다른 문제 위주로 풀었습니다.
- 자바와 병행해서 코드를 작성해봤는데, 역시 익숙한건 자바네요.
=> Merge : 안승주 bfs, greedy, sort

ParkRang/BOJ 골드5 7569 토마토.py, ParkRang/Two_pointer/BOJ 골드5 2230 수 고르기.py, ParkRang/Two_pointer/BOJ 실버3 2559 수열.py, ParkRang/Two_pointer/BOJ 실버4 1940 주몽.py
- https://www.acmicpc.net/problem/7569
- https://www.acmicpc.net/problem/2230
- https://www.acmicpc.net/problem/1940
- https://www.acmicpc.net/problem/2559
- 런타임 에러가 많이 떠서 생각보다 고생을 한 것 같네요. 에러를 줄여나가는 방법을 많이 습득해야겠다고 느꼈습니다.
=> Create code 박진우 : TwoPointer

brojoon1/bfs/BOJ 골드4 7569 토마토.py
- https://www.acmicpc.net/problem/7569
- 이번주는 공통 문제 한 문제만 풀었습니다...
다음주 부터는 3문제씩 풀겠습니다!
=> Create Code : 김형준 BOJ 골드5 7569 토마토

jian1114/bfs/이지안 BOJ 골드5 7576 토마토.py
- https://www.acmicpc.net/problem/7576
-
=> Create code : 이지안 BOJ 골드5 7569 토마토

Pang-dachu/Stack and Queue/김인재 PGS level2 기능개발.py, Pang-dachu/Stack and Queue/김인재 PGS level2 프린터.py
-  https://school.programmers.co.kr/learn/courses/30/lessons/42586
-  https://school.programmers.co.kr/learn/courses/30/lessons/42587
- https://www.acmicpc.net/problem/11659
- 이번주는 코딩 문제 풀이에 시간을 별로 못쓴거 가태요..
=> Pang dachu

brojoon1/구현/BOJ 실버3 11659 구간 합 구하기4.py, brojoon1/투 포인터/BOJ 골드4 1806 부분합.py
[구간합]
https://www.acmicpc.net/problem/11659
[부분합]
https://www.acmicpc.net/problem/1806
- 공통 문제 두 문제만 풀었습니다..
=> Merge : 김형준 투 포인터

beginner0107/DP/N타일링.java, beginner0107/DP/N타일링.py, beginner0107/수열/부분합.java, beginner0107/수열/부분합.py, beginner0107/재귀/쿼드압축.java, beginner0107/재귀/쿼드압축후개수세기.py, beginner0107/정렬/가장큰수.java, beginner0107/정렬/가장큰수.py
- 가장 큰 수: https://school.programmers.co.kr/learn/courses/30/lessons/42746
- 쿼드압축 후 개수세기: https://school.programmers.co.kr/learn/courses/30/lessons/68936
- 2 x N타일링: https://school.programmers.co.kr/learn/courses/30/lessons/12900
- 부분합: https://www.acmicpc.net/problem/1806 
- 프로그래머스 데브 매칭(코테)를 봤는데 BFS, DP, DFS 문제가 나왔네여. 
- 요번에도 자바와 파이썬 두가지 언어로 풀어봤습니다.
- 2 x N타일링 문제 분할 정복 알고리즘으로 풀어봤는데 재밌었네욥.
=> Merge : 안승주 DP, 분할 정복 알고리즘,  정렬

bokkuembab/Dijkstra/BOJ 골드5 1916 최소비용 구하기.py, bokkuembab/Dijkstra/BOJ 골드5 5972 택배 배송.py, bokkuembab/Dijkstra/BOJ 실버1 1446 지름길.py, bokkuembab/prefix sum/BOJ 실버1 11660 구간 합 구하기 5.py, bokkuembab/prefix sum/BOJ 실버3 11659 구간 합 구하기 4.py
- https://www.acmicpc.net/problem/1446
- https://www.acmicpc.net/problem/5972
- https://www.acmicpc.net/problem/1916
- https://www.acmicpc.net/problem/11659
- https://www.acmicpc.net/problem/11660
- 다익스트라의 기본 문제는 풀 수 있지만, 응용 문제는 아직 어렵네요
=> Merge : 위예진 Dijkstra

ayocado/투 포인터/BOJ 실버3 11659 구간 합 구하기4.py
- 실버3 11659번 구간 합 구하기4 : https://www.acmicpc.net/problem/11659
=> Merge : 윤용완 투 포인터

ParkRang/BOJ 실버3 11659 구간 합 구하기 4.py, ParkRang/BruteForce/BOJ 1057 실버4 토너먼트.py, ParkRang/BruteForce/BOJ 1436 실버5 영화감독 숌.py, ParkRang/BruteForce/BOJ 5555 실버5 반지.py, ParkRang/BruteForce/BOJ 실버4 1969 DNA.py
- https://www.acmicpc.net/problem/5555
- https://www.acmicpc.net/problem/1436
- https://www.acmicpc.net/problem/1057
- https://www.acmicpc.net/problem/1969
- https://www.acmicpc.net/problem/11659
- 이번 주는 참 공부가 뜻대로 되지 않았던 것 같아서, 편하게 브루트포스 풀어보았습니다.
-
=> Create code : 박진우 BruteForce

ayocado/BFS,DFS/BOJ 골드4 1987 알파벳.py, ayocado/BFS,DFS/PGS level3 43163 단어변환.py, ayocado/BFS,DFS/PGS level3 43164 여행경로.py
- BOJ 골드4 1987 알파벳 : https://www.acmicpc.net/problem/1987
- PGS level3 43163 단어변환 : https://school.programmers.co.kr/learn/courses/30/lessons/43163
- PGS level3 43164 여행경로 : https://school.programmers.co.kr/learn/courses/30/lessons/43164
- 공통 문제와 같은 BFS, DFS 알고리즘 문제를 풀었습니다.
=> Merge : 윤용완 BFS,DFS

Pang-dachu/etc/김인재 PGS level1 추억 점수.py, Pang-dachu/etc/김인재 PGS level2 k진수에서 소수 개수 구하기.py, Pang-dachu/etc/김인재 PGS level2 귤 고르기.py
- https://school.programmers.co.kr/learn/courses/30/lessons/138476
- https://school.programmers.co.kr/learn/courses/30/lessons/92335
- https://school.programmers.co.kr/learn/courses/30/lessons/176963
- 힘드러용 :(
=> Merge : 김인재 기타 문제 

beginner0107/BFS/숫자변환하기.java, beginner0107/BFS/숫자변환하기.py, beginner0107/DFS/여행경로.java, beginner0107/DFS/여행경로.py, beginner0107/구현/123나라의숫자.py, beginner0107/구현/나라의숫자.java, beginner0107/구현/삼각달팽이.java, beginner0107/구현/삼각달팽이.py, beginner0107/수열/부분합.py
- 여행경로: https://school.programmers.co.kr/learn/courses/30/lessons/43164
- 삼각달팽이: https://school.programmers.co.kr/learn/courses/30/lessons/68645
- 124나라의 숫자: https://school.programmers.co.kr/learn/courses/30/lessons/12899
- 숫자 변환하기: https://school.programmers.co.kr/learn/courses/30/lessons/154538
- 공통문제 단순하게 dict(Hash)로 풀려고 했는데 테스트 케이스 1번 하나가 계속 막히더라구요.
- 결국은 DFS or BFS로 풀어야 하더라구요. 정답을 조금 봤습니다. *_*
=> Merge : 안승주 DFS/BFS/구현

jian1114/dfs/이지안 PGS level3 43164 여행경로.py
- https://school.programmers.co.kr/learn/courses/30/lessons/43164
-
=> Create code : 이지안 PGS level3 43164 여행경로

kimyoo04/DP/BOJ 실버2 11053 가장 긴 증가하는 부분 수열.py, kimyoo04/그래프/BOG 실버3 2606 바이러스.py, kimyoo04/그래프/BOJ 실버1 2178 미로 탐색.py
- https://www.acmicpc.net/problem/11053
- https://www.acmicpc.net/problem/2606
- https://www.acmicpc.net/problem/2178
- bfs가 부족하다는 것을 느끼고 2 문제를 풀었습니다.. 공통문제는 풀다가 실패하여서 내일 커밋할 예정입니다!
=> 김유 lis, bfs

brojoon1/dfs/PGS level3 여행경로.py, brojoon1/그리디/PGS level2 구명보트.py, brojoon1/스택&큐/PGS level2 짝지어 지거하기.py
- 구명보트
https://school.programmers.co.kr/learn/courses/30/lessons/42885?language=python3
- 여행 경로
https://school.programmers.co.kr/learn/courses/30/lessons/43164
- 짝지어 제거하기
https://school.programmers.co.kr/learn/courses/30/lessons/12973
- 여행경로 공통문제 풀기
- dfs 문제 한 개, greedy 문제 한 개 프로그래머스에서 골라서 풀었습니다
=> Merge : 김형준 dfs, stack, greedy

ParkRang/DP/BOJ 골드5 15486 퇴사 2.py, ParkRang/DP/BOJ 실버2 14430 자원 캐기.py, ParkRang/DP/BOJ 실버2 17291 새끼치기.py, ParkRang/PGS LV3 여행경로.py
- https://www.acmicpc.net/problem/15486
- https://www.acmicpc.net/problem/14430
- https://www.acmicpc.net/problem/17291
- https://school.programmers.co.kr/learn/courses/30/lessons/43164
- 
- 요새 코딩이 잘 안되고 이해가 어려워서 힘들었는데 DP를 풀면서 좀 재밌었고 머리를 식히고 더 배워나갈 수 있음을 확인할 수 있어서 좋았습니다.
=> Create code : 박진우 DP

beginner0107/BFS/단어변환.py, beginner0107/DFS/네트워크.py, beginner0107/Heap/야근지수.py
- 야근지수: https://school.programmers.co.kr/learn/courses/30/lessons/12927
- 단어변환: https://school.programmers.co.kr/learn/courses/30/lessons/43163
- 네트워크: https://school.programmers.co.kr/learn/courses/30/lessons/43162
- 파이썬으로 힙 자료구조는 처음 써봤네요.
=> Merge : 안승주 BFS, DFS, Heap

jian1114/bfs/이지안 PGS level3 43163 단어변환.py
- https://school.programmers.co.kr/learn/courses/30/lessons/43163?language=python3
-
=> Create code : 이지안 PGS level3 43163 단어변환

ParkRang/01_Knapsack/BOJ 골드5 12865 평범한 배낭.py, ParkRang/01_Knapsack/BOJ 골드5 14728 벼락치기.py, ParkRang/01_Knapsack/BOJ 골드5 17845 수강 과목.py, ParkRang/PGS level3 단어변환.py
- https://school.programmers.co.kr/learn/courses/30/lessons/43163?language=java
- https://www.acmicpc.net/problem/12865
- https://www.acmicpc.net/problem/17845
- https://www.acmicpc.net/problem/14728
- DFS 다음으로 꼭 풀어보고 싶었던 Knapsack 문제를 해결해봐서 좋았습니다.
- 주말에 몸살 걸려서 못 풀 뻔 했는데 조금 나아져서 풀 수 있었습니다.
=> Create code : 박진우 01_Knapsack

brojoon1/dfs/PGS level3 단어 변환.py
- 단어 변환
https://school.programmers.co.kr/learn/courses/30/lessons/43163
- 사정상 한 문제만 올립니다..
=> Merge : 김형준 dfs

bokkuembab/BFS/PGS level3 단어 변환.py, bokkuembab/binary search/BOJ 골드5 2467 용액.py, bokkuembab/binary search/BOJ 실버2 1654 랜선 자르기.py
- https://www.acmicpc.net/problem/2467
- https://www.acmicpc.net/problem/1654
- https://school.programmers.co.kr/learn/courses/30/lessons/43163
- 늦게 올리긴 했지만 바쁘더라도 알고리즘 공부를 놓지 않을 수 있어서 좋네요ㅎㅎ
- 이진 탐색은 봐도봐도 어려운 것 같습니다
=> Merge : 위예진 binary search

heewon00/구현/PGS level2 42888 오픈채팅방.py, heewon00/구현/PGS level2 60058 괄호 변환.py, heewon00/구현/PGS level3 42627 디스크 컨트롤러.py, heewon00/힙/PGS level2 42626 더 맵게.py
https://school.programmers.co.kr/learn/courses/30/lessons/42626
https://school.programmers.co.kr/learn/courses/30/lessons/42627
https://school.programmers.co.kr/learn/courses/30/lessons/42888
https://school.programmers.co.kr/learn/courses/30/lessons/60058
=> Merge : 박희원 구현

ParkRang/PGS LV3 42627 디스크 컨트롤러.py, ParkRang/Queue/PGS LV2 42586 기능개발.py, ParkRang/Queue/PGS LV2 42587 프린터.py, ParkRang/Queue/PGS LV2 49993 스킬트리.py
- https://school.programmers.co.kr/learn/courses/30/lessons/42627
- https://school.programmers.co.kr/learn/courses/30/lessons/42587
- https://school.programmers.co.kr/learn/courses/30/lessons/42586
- https://school.programmers.co.kr/learn/courses/30/lessons/49993
- 큐를 통해서 더 쉽게 큐나 리스트를 사용할 수 있을것 같아서 편했습니다.
=> Create Code : 박진우 Queue

ayocado/힙/PGS level3 42627 디스크 컨트롤러.py
- PGS level3 42627 디스크 컨트롤러 : https://school.programmers.co.kr/learn/courses/30/lessons/42627?language=python3
- 공통 문제 밖에 풀지 못했네요,,
=> Merge : 윤용완 heap

bokkuembab/greedy/BOJ 골드5 2138 전구와 스위치.py, bokkuembab/greedy/BOJ 실버1 1080 행렬.py, bokkuembab/heap/BOJ 실버1 11286 절댓값 힙.py, bokkuembab/heap/BOJ 실버2 11279 최대힙.py, bokkuembab/heap/PGS level3 42627 디스크 컨트롤러.py
- https://www.acmicpc.net/problem/2138
- https://www.acmicpc.net/problem/1080
- https://www.acmicpc.net/problem/11279
- https://www.acmicpc.net/problem/11286
- https://school.programmers.co.kr/learn/courses/30/lessons/42627
- 공통 문제(프로그래머스 디스크컨트롤러)에서 19번 테케만 통과를 못하는데, 인터넷에서 찾아본 관련 반례들은 다 통과를 합니다ㅠㅠ 다같이 이 문제에 대해 의논해보고 싶습니다!ㅎㅎ
=> Merge : 위예진 Greedy, Heap

brojoon1/구현/PGS level3 디스크 컨트롤러.py
- https://school.programmers.co.kr/learn/courses/30/lessons/42627?language=python3
-
=> Merge : 김형준 디스크 컨트롤러

beginner0107/DP/등굣길.java, beginner0107/정렬/성지키기.java, beginner0107/정렬/줄세우기.java
- 줄 세우기: https://www.acmicpc.net/problem/10431
- 성 지키기: https://www.acmicpc.net/problem/1236
- 등굣길: https://school.programmers.co.kr/learn/courses/30/lessons/42898?language=java
- 공통문제는 고민 고민 하다가 힙 자료구조에 대해 공부하고 풀려고 합니다.
- DP문제와 정렬 문제 풀었습니당.
=> Merge : 안승주 DP, 정렬

ParkRang/BOJ 골드4 1987 알파벳.py, ParkRang/heapq/BOJ 골드5 1374 강의실.py, ParkRang/heapq/BOJ 실버2 11279 최대 힙.py, ParkRang/heapq/BOJ 실버2 1927 최소 힙.py
- https://www.acmicpc.net/problem/11279
- https://www.acmicpc.net/problem/1927
- https://www.acmicpc.net/problem/1374
- https://www.acmicpc.net/problem/1987
- heap을 쓰니 잘 풀리는 문제가 꽤 있네요
- 알파벳 문제의 경우 시간 초과가 10번 이상 나서 많이 힘들었습니다.
=> Create code : 박진우 heapq

jian1114/bfs/이지안 BOJ 골드4 1987 알파벳.py
=> Create code : 이지안 BOJ 골드4 1987 알파벳

beginner0107/브루트포스/화살표그리기.java, beginner0107/정렬/수열정렬.java, beginner0107/정렬/카드.java, beginner0107/정렬/카드2.java, beginner0107/정렬/파일정리.java
- https://www.acmicpc.net/problem/15970
- https://www.acmicpc.net/problem/20291
- https://www.acmicpc.net/problem/11652
- https://www.acmicpc.net/problem/1015
- https://www.acmicpc.net/problem/2164
- 공통문제를 까먹었네요. 허걱. 다음주에 풀어서 올리겠습니다.
=> Merge : 안승주 정렬, 브루트포스

ParkRang/PGS LV3 섬 연결하기.py, ParkRang/graph/BOJ 골드4 1197 최소 스패닝 트리.py, ParkRang/graph/BOJ 실버3 2606 바이러스.py, ParkRang/graph/BOJ 실버5 1068 트리.py
- https://www.acmicpc.net/problem/1068
- https://www.acmicpc.net/problem/1197
- https://www.acmicpc.net/problem/2606
- https://school.programmers.co.kr/learn/courses/30/lessons/42861
- kruskal 재밌었습니다.
=> Create code : 박진우 Graph

jian1114/greedy/이지안 PGS level3 42861 섬 연결하기.py
- https://school.programmers.co.kr/learn/courses/30/lessons/42861
- 크루스컬 알고리즘을 코마 1차때 본 거 같은데 다시 한 번 공부하는 계기가 되어 좋았습니다.
=> Create code : 이지안 PGS level3 42861 섬 연결하기

beginner0107/DFS/빛의경로.java, beginner0107/DFS/양궁대회.java, beginner0107/그리디/섬연결.java
- https://school.programmers.co.kr/learn/courses/30/lessons/86052
- https://school.programmers.co.kr/learn/courses/30/lessons/92342
- https://school.programmers.co.kr/learn/courses/30/lessons/42861
- 공통문제가 어려웠습니다. 답을 보고 풀었지만, union-find, 크루스칼 알고리즘에 대해 알게 되었습니다.
=> Merge : 안승주 그리디, DFS

ayocado/그리디/PGS level3 42861 섬 연결하기.py
- PGS level3 42861 섬 연결하기 :  https://school.programmers.co.kr/learn/courses/30/lessons/42861
-
=> Merge : 윤용완 그리디

heewon00/DFS, BFS/PGS level2 1844 게임 맵 최단거리.py, heewon00/DFS, BFS/PGS level2 43165 타겟 넘버.py
https://school.programmers.co.kr/learn/courses/30/lessons/1844
https://school.programmers.co.kr/learn/courses/30/lessons/43165
https://school.programmers.co.kr/learn/courses/30/lessons/42861
=> Merge : 박희원 bfs

bokkuembab/Dijkstra/PGS level3 42861 섬 연결하기.py, bokkuembab/back tracking/BOJ 실버3 15649 N과 M (1).py
- https://www.acmicpc.net/problem/15649
- https://school.programmers.co.kr/learn/courses/30/lessons/42861
- 다음에는 3문제 이상 풀어오겠습니다ㅠㅠ
=> Merge : 위예진 back tracking

ParkRang/Knapsack/BOJ 골드5 3067 Coins.py, ParkRang/Knapsack/BOJ 실버2 1535 안녕.py, ParkRang/Knapsack/PGS LV3 거스름돈.py, ParkRang/PGS LV2 17683 방금그곡.py
- https://www.acmicpc.net/problem/1535
- https://www.acmicpc.net/problem/3067
- https://school.programmers.co.kr/learn/courses/30/lessons/12907
- https://school.programmers.co.kr/learn/courses/30/lessons/17683
- 냅색이 중요한 알고리즘이라 생각하여 다시 공부하였습니다.
=> Create code : 박진우 Knapsack

Pang-dachu/etc/김인재 PGS level2 뒤에있는큰수찾기.py, Pang-dachu/etc/김인재 PGS level2 롤케이크 자르기.py
=> Merge : 김인재 PGS연습문제

bokkuembab/BFS/BOJ 실버2 2644 촌수계산.py, bokkuembab/Dijkstra/BOJ 골드4 1753 최단경로.py, bokkuembab/simulation/PGS 12977 level1 소수만들기.py
- https://school.programmers.co.kr/learn/courses/30/lessons/12977
- https://www.acmicpc.net/problem/2644
- https://www.acmicpc.net/problem/1753
-
=> Merge : 위예진 BFS, Dijkstra

ParkRang/DP/BOJ 실버1 1932 정수 삼각형.py, ParkRang/DP/BOJ 실버2 4097 수익.py, ParkRang/DP/BOJ 실버5 1010 다리 놓기.py
- https://www.acmicpc.net/problem/1010
- https://www.acmicpc.net/problem/1932
- https://www.acmicpc.net/problem/4097
- DP는 많이 풀어보고 생각을 많이 해보는게 답인것 같습니다.
=> Create code : 박진우 DP2

heewon00/DP/BOJ 골드5 9251 LCS.py, heewon00/DP/BOJ 실버2 14430 자원 캐기.py, heewon00/DP/BOJ 실버4 2839 설탕 배달.py
https://www.acmicpc.net/problem/2839
https://www.acmicpc.net/problem/14430
https://www.acmicpc.net/problem/9251
=> Merge : 박희원 DP

Pang-dachu/Heap/BOJ 실버1 11286 절댓값 힙.py, Pang-dachu/Heap/BOJ 실버2 11279 최대 힙.py, Pang-dachu/Heap/BOJ 실버2 1927 최소 힙.py, Pang-dachu/Heap/BOJ 실버2 2075 N번째 큰 수.py
- https://www.acmicpc.net/problem/11286
- https://www.acmicpc.net/problem/1927
- https://www.acmicpc.net/problem/2075 
- https://www.acmicpc.net/problem/11279
-  점점 코딩할 줄 모르게 되는거 같은 느낌 :(
=> PR : 김인재 Heap

beginner0107/DFS/불량사용자.java, beginner0107/DP/자원캐기.java, beginner0107/그리디/기지국.java, beginner0107/해시/베스트앨범.java, beginner0107/해시/베스트앨범.py
- https://www.acmicpc.net/problem/14430
- https://school.programmers.co.kr/learn/courses/30/lessons/64064
- https://school.programmers.co.kr/learn/courses/30/lessons/12979
- https://school.programmers.co.kr/learn/courses/30/lessons/42579
-
=> Merge : 안승주 해시, DFS, 그리디, DP

jian1114/dp/이지안 BOJ 실버2 14430 자원캐기.py
- https://www.acmicpc.net/status?user_id=jian1114&problem_id=14430&from_mine=1
-
=> Create code : 이지안 BOJ 실버2 14430 자원캐기

brojoon1/DP/BOJ 실버2 14430 자원캐기.py
- https://www.acmicpc.net/problem/14430
-
=> Merge : 김형준 자원캐기

ayocado/DP/BOJ 실버2 14430 자원 캐기.py
- BOJ 실버2 14430 자원 캐기 : https://www.acmicpc.net/problem/14430
=> Merge : 윤용완 DP

beginner0107/구현/연속펄스부분수열의합.java, beginner0107/그래프/순위.java, beginner0107/트리/다단계칫솔판매.java
- https://school.programmers.co.kr/learn/courses/30/lessons/161988
- https://school.programmers.co.kr/learn/courses/30/lessons/49191
- https://school.programmers.co.kr/learn/courses/30/lessons/77486
-
=> Merge : 안승주 구현, 그래프, 트리

beginner0107/구현/파괴되지않은건물.java
- https://school.programmers.co.kr/learn/courses/30/lessons/92344
- 어 왜 이렇게 커밋이?
=> Merge : 누적합
